[package]
name = "brainfuck_compiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs

[dependencies]
codemap = "0.1"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"


